version: '3.8'

services:
  postegres:
    image: postgres
    container_name: postgres-docker
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-docker
    restart: always
    ports:
      - 5050:80
    env_file:
      - ../.env